export const VALIDATION_RULES = {
  USER: {
    USERNAME_MIN_LENGTH: 3,
    USERNAME_MAX_LENGTH: 30,
    PASSWORD_MIN_LENGTH: 6,
    PASSWORD_MAX_LENGTH: 128,
    NAME_MIN_LENGTH: 1,
    NAME_MAX_LENGTH: 50,
  },
  CHAT: {
    NAME_MIN_LENGTH: 1,
    NAME_MAX_LENGTH: 100,
    DESCRIPTION_MAX_LENGTH: 500,
    MAX_PARTICIPANTS: 100,
  },
  MESSAGE: {
    CONTENT_MAX_LENGTH: 4000,
    MAX_ATTACHMENTS: 5,
    MAX_FILE_SIZE: 10 * 1024 * 1024, // 10MB
  },
} as const
